#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import tempfile
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import UTC, datetime
from pathlib import Path
from xml.etree import ElementTree

from bs4 import BeautifulSoup
from markdownify import markdownify

HOST = "www.weex.com"
SITEMAP_URL = f"https://{HOST}/api-doc/sitemap.xml"
CONTRACT_PREFIX = f"https://{HOST}/api-doc/contract/"
ENDPOINT_RE = re.compile(r"\b(GET|POST|PUT|PATCH|DELETE)\s+(/capi/[^\s`]+)", re.IGNORECASE)


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[3]
    parser = argparse.ArgumentParser(description="Snapshot current WEEX V3 contract docs as Markdown.")
    parser.add_argument("--output", type=Path, default=repo_root / "docs" / "api")
    parser.add_argument("--locale", default="zh-CN")
    parser.add_argument("--workers", type=int, default=6)
    parser.add_argument("--limit", type=int, default=0, help="Fetch only N pages for script testing")
    parser.add_argument("--resolve-via-doh", action=argparse.BooleanOptionalAction, default=True)
    return parser.parse_args()


def doh_ipv4(host: str) -> str:
    url = "https://dns.google/resolve?" + urllib.parse.urlencode({"name": host, "type": "A"})
    request = urllib.request.Request(url, headers={"Accept": "application/dns-json"})
    with urllib.request.urlopen(request, timeout=15) as response:  # noqa: S310 - fixed HTTPS authority
        payload = json.load(response)
    addresses = [answer["data"] for answer in payload.get("Answer", []) if answer.get("type") == 1]
    if not addresses:
        raise RuntimeError(f"DoH returned no IPv4 address for {host}")
    return addresses[0]


def fetch(url: str, resolve_ip: str | None) -> str:
    command = ["curl", "-fsSL", "--max-time", "30"]
    if resolve_ip:
        command.extend(["--resolve", f"{HOST}:443:{resolve_ip}"])
    command.append(url)
    result = subprocess.run(command, check=True, capture_output=True, text=True)
    return result.stdout


def sitemap_urls(xml_text: str, locale: str) -> list[str]:
    root = ElementTree.fromstring(xml_text)
    namespace = "{http://www.sitemaps.org/schemas/sitemap/0.9}loc"
    urls = [node.text or "" for node in root.iter(namespace)]
    current = sorted(url for url in urls if url.startswith(CONTRACT_PREFIX) and "/V2/" not in url)
    if locale:
        current = [url.replace("/api-doc/contract/", f"/api-doc/{locale}/contract/", 1) for url in current]
    return current


def page_path(url: str) -> Path:
    marker = "/contract/"
    relative = urllib.parse.urlparse(url).path.split(marker, 1)[1].strip("/") or "intro"
    safe_parts = [re.sub(r"[^A-Za-z0-9._-]+", "-", part) for part in relative.split("/")]
    return Path("contract", *safe_parts).with_suffix(".md")


def convert_page(url: str, html: str, synced_at: str) -> tuple[str, str, list[str]]:
    soup = BeautifulSoup(html, "html.parser")
    article = soup.select_one("main article")
    if article is None:
        raise RuntimeError(f"no main article found: {url}")
    for node in article.select("nav, button, script, style"):
        node.decompose()
    heading = article.find(["h1", "h2"])
    title = heading.get_text(" ", strip=True) if heading else urllib.parse.urlparse(url).path.rsplit("/", 1)[-1]
    plain_text = article.get_text(" ", strip=True)
    body = markdownify(str(article), heading_style="ATX", bullets="-")
    body = re.sub(r"\n{3,}", "\n\n", body).strip()
    body = "\n".join(line.rstrip() for line in body.splitlines())
    endpoints = sorted({f"{method.upper()} {path.rstrip('.,;')}" for method, path in ENDPOINT_RE.findall(plain_text)})
    header = (
        "<!-- Generated by skills/weex-api-development/scripts/sync_docs.py; do not edit. -->\n\n"
        f"> Source: [{url}]({url})\n\n"
        f"> Synced: {synced_at}\n\n"
    )
    return title, header + body + "\n", endpoints


def sync_page(url: str, resolve_ip: str | None, synced_at: str) -> dict[str, object]:
    title, markdown, endpoints = convert_page(url, fetch(url, resolve_ip), synced_at)
    return {
        "url": url,
        "path": page_path(url).as_posix(),
        "title": title,
        "endpoints": endpoints,
        "markdown": markdown,
        "sha256": hashlib.sha256(markdown.encode()).hexdigest(),
    }


def write_snapshot(output: Path, pages: list[dict[str, object]], synced_at: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temp_root = Path(tempfile.mkdtemp(prefix="weex-docs-", dir=output.parent))
    try:
        ordered_pages = sorted(pages, key=lambda item: str(item["path"]))
        endpoint_lines = ["# WEEX V3 Contract Endpoint Index", "", f"Synced: {synced_at}", ""]
        for page in ordered_pages:
            target = temp_root / str(page["path"])
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(str(page["markdown"]), encoding="utf-8")
            relative = target.relative_to(temp_root).as_posix()
            endpoints = page["endpoints"] or ["Documentation"]
            for endpoint in endpoints:
                endpoint_lines.append(f"- `{endpoint}` - [{page['title']}]({relative})")
        (temp_root / "ENDPOINTS.md").write_text("\n".join(endpoint_lines) + "\n", encoding="utf-8")
        manifest = {
            "source": SITEMAP_URL,
            "synced_at": synced_at,
            "page_count": len(pages),
            "pages": [
                {key: page[key] for key in ("url", "path", "title", "endpoints", "sha256")} for page in ordered_pages
            ],
        }
        (temp_root / "manifest.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        (temp_root / "README.md").write_text(
            "# Local WEEX API Snapshot\n\n"
            "Generated from the official WEEX V3 contract documentation. Do not edit generated pages manually.\n\n"
            "```bash\nuv run python skills/weex-api-development/scripts/sync_docs.py\n```\n\n"
            "Start with [ENDPOINTS.md](ENDPOINTS.md); each page links back to the official source "
            "and records its sync date.\n",
            encoding="utf-8",
        )
        if output.exists():
            shutil.rmtree(output)
        temp_root.replace(output)
    except Exception:
        shutil.rmtree(temp_root, ignore_errors=True)
        raise


def main() -> int:
    args = parse_args()
    if args.workers < 1:
        raise SystemExit("--workers must be at least 1")
    resolve_ip = doh_ipv4(HOST) if args.resolve_via_doh else None
    urls = sitemap_urls(fetch(SITEMAP_URL, resolve_ip), args.locale)
    if args.limit:
        urls = urls[: args.limit]
    synced_at = datetime.now(UTC).isoformat(timespec="seconds")
    pages: list[dict[str, object]] = []
    failures: list[str] = []
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {executor.submit(sync_page, url, resolve_ip, synced_at): url for url in urls}
        for future in as_completed(futures):
            try:
                pages.append(future.result())
            except Exception as exc:  # noqa: BLE001 - aggregate every failed page before aborting
                failures.append(f"{futures[future]}: {exc}")
    if failures:
        raise SystemExit("documentation sync failed; existing snapshot preserved:\n" + "\n".join(sorted(failures)))
    write_snapshot(args.output.resolve(), pages, synced_at)
    print(f"Synced {len(pages)} WEEX V3 contract pages to {args.output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
